name: Backend CD - Deploy Backend Services to AKS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - 'k8s/**'
      - '.github/workflows/backend-cd.yml'

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RG }} \
                                 --name ${{ secrets.AKS_NAME }} \
                                 --overwrite-existing

      - name: Attach ACR
        run: |
          az aks update --name ${{ secrets.AKS_NAME }} \
                        --resource-group ${{ secrets.AKS_RG }} \
                        --attach-acr ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Deploy Backend Infrastructure
        run: |
          cd k8s/
          kubectl apply -f configmaps.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f product-db.yaml
          kubectl apply -f order-db.yaml

      - name: Deploy Backend Services
        run: |
          cd k8s/
          kubectl apply -f product-service.yaml
          kubectl apply -f order-service.yaml

      - run: az logout
        if: always()
