name: Frontend CD - Deploy Frontend to AKS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'k8s/**'
      - '.github/workflows/frontend-cd.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az aks get-credentials --resource-group ${{ secrets.AKS_RG }} --name ${{ secrets.AKS_NAME }} --overwrite-existing

      - run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}

      - name: Deploy Frontend
        run: |
          cd k8s/
          kubectl set image deployment/frontend frontend=${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}

      - run: az logout
        if: always()
