name: Frontend CD - Deploy Frontend to AKS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'k8s/**'
      - '.github/workflows/frontend-cd.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RG }} \
            --name ${{ secrets.AKS_NAME }} \
            --overwrite-existing

      - name: ACR login
        run: az acr login --name $(echo ${{ env.ACR_LOGIN_SERVER }} | cut -d. -f1)

      - name: Ensure namespace exists
        run: kubectl create namespace ecommerce --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/ -n ecommerce

      - name: Update Frontend image
        run: |
          kubectl set image deployment/frontend \
            frontend-container=${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} \
            -n ecommerce

      - name: Wait for rollout
        run: kubectl rollout status deployment/frontend -n ecommerce

      - run: az logout
        if: always()
